[project]
name = "cc-django"
version = "0.1.0"
description = "Cookiecutter for Django projects singularIT"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
