[project]
name = "cc-django"
version = "0.1.0"
description = "Cookiecutters for python projects @singularIT"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "pre-commit>=4.2.0",
]

[dependency-groups]
dev = [
]
