stages:
  - lint
  - test
  - deploy

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
  - component: singular-code.de/singularit/ci-components/utilities/size/all@1.2.0

variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_DB: {{ cookiecutter.project_slug }}
  POSTGRES_USER: {{ cookiecutter.project_slug }}
  POSTGRES_PASSWORD: {{ cookiecutter.project_slug }}
  UV_LINK_MODE: copy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED == 'false'
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_PROTECTED == 'true'
