name: ci.yml
on:
    push:

jobs:
  django-template-test:
    name: Django Template Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.12, 3.13]
        postgresql_version: [16, 17]
        username_type: [email, username]
        use_drf: [y, n]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run Django Template Tests
        run: |
          uvx cookiecutter django -v --no-input -o test/ \
            python_version=${{ matrix.python_version }} \
            postgresql_version=${{ matrix.postgresql_version }} \
            username_type=${{ matrix.username_type }} \
            use_drf=${{ matrix.use_drf }}
